# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20170326_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='level',
            new_name='program',
        ),
    ]
