# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20170401_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.ChapterPage'),
        ),
    ]
