# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0008_auto_20170401_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_false_answer', models.BooleanField(default=False)),
                ('essay_answer', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('option_answers', models.ManyToManyField(to='academy.Option')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_question_answers', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_question_answers', to='academy.Test')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_question_answers', to='academy.TestQuestion')),
            ],
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='student',
        ),
        migrations.DeleteModel(
            name='EssayAnswer',
        ),
    ]
