# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_auto_20170407_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestionanswer',
            name='points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
