# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 12:14
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_testquestionanswer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpage',
            name='content',
            field=redactor.fields.RedactorField(default='q'),
            preserve_default=False,
        ),
    ]
