# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 05:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_testquestionanswer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='q'),
            preserve_default=False,
        ),
    ]
