# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 08:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0012_auto_20170408_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 60)),
        ),
        migrations.AddField(
            model_name='testquestionanswer',
            name='essay_answer_content',
            field=redactor.fields.RedactorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testquestionanswer',
            name='true_false_answer',
            field=models.NullBooleanField(),
        ),
        migrations.RemoveField(
            model_name='testquestionanswer',
            name='essay_answer',
        ),
        migrations.RemoveField(
            model_name='testquestionanswer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testquestionanswer',
            name='test',
        ),
        migrations.AlterUniqueTogether(
            name='testquestionanswer',
            unique_together=set([('student', 'test_question')]),
        ),
    ]
